### ISSUE TITLE
Unknown normalization when rendering crops from spatial samples. 

### ISSUE THREAD

**Issue by rushin682** [scverse/spatialdata-plot#290]
Hi developers,

Thanks for the amazing framework. I am using the framework to extract non-linear features from image patches of visium samples. When performing some QC on the data, I noticed that the image renders of cropped patches have some sort of normalization which doesn't exist in the original image when loaded in QuPath or Openslide (https://openslide.org/api/python/).

Please find attached images. I tried to find the normalization function in the plot code, but without success.

Can you please help? Knowing what kind of normalization is used is crucial to minimise batch-effect in SOTA Histopathology analysis methods. If possible it would be great also to disable normalization by default since for different tissue images, the rendered normalizations shows vast differences in how the different stains are represented.

<img width="568" alt="spatialdata-render" src="https://github.com/scverse/spatialdata/assets/26457882/3cdcbd32-a285-4100-b40e-86237ac79048">

<img width="568" alt="openslide-patch" src="https://github.com/scverse/spatialdata/assets/26457882/42dd1d2b-fc69-40ac-b8a8-ed3f82c6df49">

**Comment by LucaMarconato** [comment]
I actually dug more into this and it looks like that the behavior is due to a side effect of the normalization strategy used in `spatialdata-plot`.

I could reproduce this on the Visium HD notebook. The full resolution image has `unit` values in `{0, ... 255}`, and we have that `spatialdata_plot.pl.render._render_images()`, in the piece of code highlighted in the screenshot, the problem arises.
<img width="685" alt="image" src="https://github.com/user-attachments/assets/2ded6ced-9a2f-4fea-b6b3-bafd299c6858">

Precisely, for the `Visium_HD_Mouse_Small_Intestine_hires_image` image and for `c=1`, we have that
```python
layers[c].data.compute().min() == 0
```
but 
```python
render_params.cmap_params.norm(layers[c]).data.min() == -0.15
```

This leads to the warning
```
_log.warning(
              'Clipping input data to the valid range for imshow with '
              'RGB data ([0..1] for floats or [0..255] for integers).'
          )
```
in `matploptlib.image._ImageBase._normalize_image_array()`.

**Comment by LucaMarconato** [comment]
> Can you please help? Knowing what kind of normalization is used is crucial to minimise batch-effect in SOTA Histopathology analysis methods. If possible it would be great also to disable normalization by default since for different tissue images, the rendered normalizations shows vast differences in how the different stains are represented.

On the positive side, @rushin682 I confirm that the downstream analysis would not be affected as this behavior only affects plotting, and the normalized data is never exposed outside the `spatialdata-plot` library.

**Comment by timtreis** [comment]
hey @rushin682, will merge the linked PR later this week. I think that should fix your issue. Would be happy for you to test with that branch 👍
